# Generated by Django 2.2.19 on 2022-12-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followings',
            new_name='following',
        ),
    ]
