# Generated by Django 2.2.19 on 2023-01-06 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230106_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='recipe',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_carts', to='recipes.Recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
