# Generated by Django 2.2.19 on 2023-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20230107_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=7, unique=True, verbose_name='Цвет в HEX'),
            preserve_default=False,
        ),
    ]
