name: foodgram workflow

on: [push]

jobs:
  
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 
    - name: Login to Docker 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2 
      with:
        context: foodgram_backend/
        push: true
        tags: etozheigor/foodgram_backend:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/master'
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
            sudo docker-compose stop
            sudo docker image rm etozheigor/foodgram_backend
            sudo docker pull etozheigor/foodgram_backend
            sudo docker-compose up -d --build
            docker-compose exec etozheigor-backend-1 python manage.py makemigrations
            docker-compose exec etozheigor-backend-1 python manage.py migrate
            docker-compose exec etozheigor-backend-1 python manage.py collectstatic --no-input 

